routes:

collections:
  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:gallery'
    data: page.home
  /posts/:
    permalink: /{slug}/
    template: posts
    data: page.posts
    filter: 'featured:false'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/